In [19]:
import pandas as pd
import numpy as np
import redis

In [20]:
r = redis.Redis(host='localhost', port=6379, db=0)

In [21]:
df= pd.read_excel('C:/Users/49152/Downloads/Ojal/IS-Redis/monster_com-job_sample.xls')

In [22]:
df.head(5)

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,Type,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,United States of America,US,2016-10-05,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",organization,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,United States of America,US,2016-10-06,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,United States of America,US,2016-10-07,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United States of America,US,2016-10-08,No,jobs.monster.com,Why Join Altec? If you‚Äôre considering a care...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States of America,US,2016-10-09,No,jobs.monster.com,Position ID#¬† 76162 # Positions¬† 1 State¬† C...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.drop(df.iloc[:, 14:256], inplace = True, axis = 1)
df

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,Type,page_url,salary,sector,uniq_id
0,United States of America,US,2016-10-05,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",organization,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,2016-10-06,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,2016-10-07,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,2016-10-08,No,jobs.monster.com,Why Join Altec? If you‚Äôre considering a care...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States of America,US,2016-10-09,No,jobs.monster.com,Position ID#¬† 76162 # Positions¬† 1 State¬† C...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16378,United States of America,US,2018-06-02,No,jobs.monster.com,Job Description Job #: ¬†683789Security Engine...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16379,United States of America,US,2018-06-03,No,jobs.monster.com,Position Purpose:Associates in Office/Store Su...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16380,United States of America,US,2018-06-04,No,jobs.monster.com,Report this job About the Job Vejars technolog...,Monster,"Full Time, Employee",Phone 972-544-6786,Computer Software,http://jobview.monster.com/excellent-marketing...,NaN,NaN,482a4aad16796736f27e2cf142b1f910
16381,United States of America,US,2018-06-05,No,jobs.monster.com,Location¬† US-TX-Plano ID¬† 85728 Category¬† N...,Part Time Consulting Dietitian - Plano Job in ...,"Part Time, Employee","Plano, TX",NaN,http://jobview.monster.com/part-time-consultin...,NaN,Medical/Health,8375cb64dc9fc9e4e0b28e68f8f9eea5
16382,United States of America,US,2018-06-06,No,jobs.monster.com,Overview ¬† Let's Grow Together! We are a fast...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
conn = redis.Redis('localhost')

user1 = {"Name":"Pradeep", "Company":"SCTL", "Address":"Mumbai", "Location":"RCP"}
user2 = {"Name":"Praveen", "Company":"IBM", "Address":"Mumbai", "Location":"RCP"}

In [25]:
r.hmset("pythonDict1", user1)
r.hmset("pythonDict2", user2)

r.hgetall("pythonDict3")

C:\Users\49152\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Redis.hmset() is deprecated. Use Redis.hset() instead.
  """Entry point for launching an IPython kernel.
C:\Users\49152\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Redis.hmset() is deprecated. Use Redis.hset() instead.

{}

In [ ]:
df['date_added']=df['date_added'].astype(str)

In [29]:
for i in range(1):
    s = {"country":df['country'][i], "country_code":df['country_code'][i], "date_added":df['date_added'][i], "has_expired":df['has_expired'][i],"job_board":df['job_board'][i],"job_description":df['job_description'][i],"job_title":df['job_title'][i],"location":df['location'][i],"Type":df['Type'][i],"page_url":df['page_url'][i],"salary":df['salary'][i],"uniq_id":df['uniq_id'][i]}
    r.hmset("dict",s)

C:\Users\49152\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Redis.hmset() is deprecated. Use Redis.hset() instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [30]:
r.hgetall("dict")

{b'location': b'Madison, WI 53702',
 b'date_added': b'2016-10-05',
 b'job_description': b"TeamSoft is seeing an IT Support Specialist to join our client in Madison, WI. The ideal candidate must have at least 6 years of experience in the field. They need to be familiar with a variety of the field's concepts, practices, and procedures as this po",
 b'uniq_id': b'11d599f229a80023d2f40e7c52cd941e',
 b'country': b'United States of America',
 b'salary': b'nan',
 b'page_url': b'http://jobview.monster.com/it-support-technician-job-madison-wi-us-167855963.aspx?mescoid=1500134001001&jobPosition=20',
 b'job_board': b'jobs.monster.com',
 b'job_title': b'IT Support Technician Job in Madison',
 b'country_code': b'US',
 b'Type': b'organization',
 b'has_expired': b'No'}